---

- name: Deploy/Update webservers(s)
  hosts: all
  tasks:
    
    - name: Install apache2 package
      apt:
        name: apache2
        state: latest
    
    - name: Start and enable apache2 service
      service:
        name: apache2
        enabled: true
        state: started

    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          Webserver(s) deployed succesfully!
