---

- hosts: all
  become: true
  tasks:

  - name: Update cache
    apt:
      update_cache: yes
      cache_valid_time: 600

  - name: Upgrade distributions
    apt:
      upgrade: dist

  - name: Clean old packages
    apt:
      autoremove: yes
      autoclean: yes
