---
- hosts: testhosts
  become: yes
  
  ldap_auth:
    server_uri: ldap://ldap.lan/
    bind_dn: cn=admin,dc=ldap,dc=lan
    bind_pw: admin

  vars_prompt:
    - name: USERNAME
      prompt: 'What is the username you want to remove?'
      private: no

  tasks:
    - name: Removing user: {{ USERNAME }}
      community.general.ldap_entry:
        dn: uid={{ USERNAME }},ou=users,dc=ldap,dc=lan
        state: absent
      args: "{{ ldap_auth }}"
