---
- hosts: testhosts
  become: yes
  vars:
    USERNAME: {{{FIRSTNAME[0]}+{LASTNAME} | trim}}
    ldap_auth:
      server_uri: ldap://ldap.lan/
      bind_dn: cn=admin,dc=ldap,dc=lan
      bind_pw: admin

  vars_prompt:
    - name: FIRSTNAME
      prompt: 'What is the first name?'
      private: no
      
    - name: LASTNAME
      prompt: 'What is the last name?'
      private: no

    - name: PASSWORD
      prompt: 'What is the new password?'
      private: yes
      encrypt: sha512_crypt
      salt_size: 7

    - name: GROUP
      prompt: 'What role must be assigned to the new user? (guest, employee, administrator)'
      private: no

  tasks:
    - name: 'Creating: "{{ USERNAME }}"'
      community.general.ldap_entry:
        dn: uid="{{ USERNAME }}",ou=users,dc=ldap,dc=lan
        objectClass: posixAccount
      args: "{{ ldap_auth }}"
